name: release-prd
on:
  workflow_dispatch:
    inputs:
      version:
        description: "version"
        required: true
        type: string

jobs:
  release-prd:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: git tags
      - run: go install github.com/suzuito/sandbox2-common-go/tools/release/cmd/increment-release-version@latest
      - run: echo $PATH
      - run: $(go env GOPATH)/bin/increment-release-version
      - run: bash create-release-draft.sh ${{ inputs.version }} ${{ github.ref }}
        env:
          GH_TOKEN: ${{ github.token }}
