name: release-prd
on:
  workflow_dispatch:
    inputs:
      increment:
        description: "increment"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release-prd:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch all history for all branches and tags
          fetch-tags: true
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - run: go install github.com/suzuito/sandbox2-common-go/tools/release/cmd/increment-release-version@v0.0.1
      - run: increment-release-version -increment ${{ inputs.increment }} -branch ${{ github.ref }} -prefix v -git /usr/bin/git -owner suzuito -repo sandbox2-common-go -token ${{ github.token }}
