name: release-prd
on:
  workflow_dispatch:
    inputs:
      increment:
        description: "increment"
        required: true
        type: choice
        options:
          - patch
          - minor

jobs:
  release-prd:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch all history for all branches and tags
          fetch-tags: true
      - run: curl -LO https://github.com/suzuito/sandbox2-common-go/releases/download/v0.12.1/tools-linux-amd64.tar.gz && tar xzvf tools-linux-amd64.tar.gz
      - run: ./increment-release-version -increment ${{ inputs.increment }} -branch ${{ github.ref }} -prefix v -git /usr/bin/git -owner suzuito -repo sandbox2-common-go -token ${{ github.token }}
